services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - STRIPE_SECRET_KEY=your_stripe_secret_key

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: rom
      POSTGRES_PASSWORD: rom
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  db_data:
