services:
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - STRIPE_SECRET_KEY=your_stripe_secret_key
    volumes:
      - ./data:/app
